trigger:
  paths:
    include:
      - app/helmchart/**

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'k8s-dev'
- name: namespace
  value: 'default'
- name: artifactName 
  value: 'helmchart'

stages:
  - stage: Publish
    displayName: Publish Artifact
    jobs:
      - job: PublishHelmArtifact
        displayName: Publish Helm Artifact
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Manifest
            inputs:
              artifactName: $(artifactName)
              path: $(artifactName)

  - stage: Deploy
    jobs:
    - deployment: DeployAKS
      displayName: Deploy AKS
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: $(artifactName)

              - task: AzureCLI@2
                displayName: Get AKS Credentials
                inputs:
                  azureSubscription: $(serviceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    echo "Getting AKS credentials..."
                    az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing  

              - task: HelmDeploy@1
                displayName: Helm Upgrade/Install
                inputs:
                  connectionType: 'Azure Resource Manager'
                  azureSubscription: $(serviceConnection)
                  azureResourceGroup: $(aksResourceGroup)
                  kubernetesCluster: $(aksCluster)
                  namespace: $(namespace)
                  command: upgrade
                  chartType: FilePath
                  chartPath: '$(Pipeline.Workspace)/$(artifactName)/'
                  releaseName: 'online-store'
                  install: true
                  waitForExecution: false                  