trigger:
  paths:
    include:
      - app/order-service/**

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'k8s-dev'
- name: imageTag
  value: $(Build.BuildId)
- name: imageName
  value: 'order'

stages:
  - stage: Build
    displayName: Build and Publish
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build and Publish Docker Images
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker
            inputs:
              dockerVersion: '17.09.0-ce'

          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: $(acrServiceConnection)
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/order-service/Dockerfile'
              tag: $(imageTag)