trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'arm-svc-con'
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  acrServiceConnection: 'acr-svc-connection'
  acrName: 'acronlinestoredevuksouth001'
  namespace: 'default'
  environment: "dev"
  artifactName: 'manifests'
  imageTag: $(Build.BuildId)   
  imageName: 'store-front'

stages:
  - stage: Build
    displayName: Build and Publish
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build Publish Docker Images
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker
            inputs:
              dockerVersion: '17.09.0-ce'

          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: $(acrServiceConnection)
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/store-front/Dockerfile'
              tag: $(imageTag)

          - task: PublishPipelineArtifact@1
            displayName: Publish Manifest
            inputs:
              artifactName: $(artifactName)
              path: $(artifactName)

  - stage: Deploy
    jobs:
    - deployment: DeployAKS
      displayName: Deploy AKS
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: $(artifactName)

              - script: |
                  echo "Workspace Directory: $(Pipeline.Workspace)"
                  ls -R "$(Pipeline.Workspace)"

              - task: AzureCLI@2
                displayName: Get AKS Credentials
                inputs:
                  azureSubscription: $(serviceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    echo "Getting AKS credentials..."
                    az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing

                    echo "Updating deployment files with image tags..."
                    sed -i "s|acronlinestoredevuksouth001.azurecr.io/store-front|$(acrName).azurecr.io/store-front:$(imageTag)|g" $(Pipeline.Workspace)/manifests/store-front-deployment.yml
                  
                    echo "Deploying to AKS..."
                    kubectl apply -f $(Pipeline.Workspace)/manifests/store-front-deployment.yml -n $(namespace)  
                    kubectl apply -f $(Pipeline.Workspace)/manifests/store-front-service.yml -n $(namespace) 

                    echo "Deployment completed."